language: swift
osx_image: xcode10.2

cache:
  directories:
  - Carthage

install:
  - bundle install

script:
  - fastlane buildCI

notifications:
  slack:
    secure: PQcPQT5gM/0P2cSlVQ+BW1YkPXTzfcha4ZMwPcRxYLotROaHiy802daaQ9Twg4hgpHFW8Y6vcpQtFEnRGm1eqf2FiHXt470r2/9AuwVewkTSKaTfhpc3kQ3RlvngUghf3qHKqJTOCcN/jAoiKd6v60DOgptd589NBy29frqpBdEUl4NL7CWNltvCzVFlC8PKHcHLEYnVig8XrlGOb2zf2Qf6Z22RgSsy6c6SuUX6YmaPAvHe5PfAYyHAhFvF9F2ZnE6tNxpIEIXkB2F5wbr9RThqbWVEEqVvHSKttfquXH5NSgQ3VbV03uF5ZIDm/bqEUSSSio9G05GiP8QUgzhOl7pslUysgdOjHGU1yTxmZZzvi8Ajy0OTBdCsSvg2aZaT5Zpied7NOucju+NNpI7mSioBcMqZ4Rz4E2MNv0ZV510bTTqvEAZyZcmSHCUm7jHJJf3gN496iAs48/UHkfXyfMX6eL5Nml7YqTnZtppiVZgH64TmTBr9d4qk3BsheGflENMvkQHhOQ2RXmAaJAZm8niEVUONsS6g+XsLDFGfeuNcB+QMOLqlGtJ6aFAIEhLWR9wpXyYVoGMCSmRkkuGDXj6nR0BD1VGMxgx+s3hwPBLokut0jkXyuVfSR7UvwrC9ZZGMPG2mfu4nFuCjetTPUq7YQ6Fb/4lzWpGL8Z2s4C0=
